name: Build and scan Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest
    - name: Sysdig Secure Inline Scan
  # You may pin to the exact commit or the version.
  # uses: sysdiglabs/scan-action@768d7626a14897e0948ea89c8437dd46a814b163
      uses: sysdiglabs/scan-action@v3.2.0
      with:
        image-tag: "sysdiglabs/dummy-vuln-app:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: us2.app.sysdig.com
        
        
    
    
        
